build:
  commands:
    build:
      - npm install
      - npm run build
  env:
    NODE_ENV: production

run:
  command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8080"]
  env:
    PYTHONPATH: "."
  resources:
    memory: 6G
    cpus: 2
