build:
  commands:
    build:
      - pip install -r requirements.txt
      - npm install
      - npm run build
  env:
    NODE_ENV: production

run:
  command: ["npm", "start"]
  env:
    PYTHONPATH: "."
    LAKEBASE_ENDPOINT:
      valueFrom: postgres
    DATABRICKS_WAREHOUSE_ID:
      valueFrom: sql-warehouse
  resources:
    memory: 6G
    cpus: 2
